language: node_js
node_js:
  - "4.0"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --samwineshop --token $1//03JLAIX3XZv9XCgYIARAAGAMSNwF-L9Ir-idEJzHT2G5YqNXFMLxK-p01xPf7oE8dEXGtj95rs9EJCkQjDbCO-bQpuE-MDSQCJt4
